<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'comm\\comm' => '/../src/service/comm/Comm.php',
                'comm\\link' => '/../src/service/comm/Link.php',
                'comm\\mailer' => '/../src/service/comm/Mailer.php',
                'comm\\messager' => '/../src/service/comm/Messager.php',
                'comm\\notification' => '/../src/service/comm/Notification.php',
                'contract\\controller' => '/../src/contract/Controller.php',
                'contract\\event' => '/../src/contract/Event.php',
                'contract\\eventlistener' => '/../src/contract/EventListener.php',
                'contract\\message' => '/../src/contract/Message.php',
                'contract\\quantity' => '/../src/contract/Quantity.php',
                'contract\\request' => '/../src/contract/Request.php',
                'contract\\response' => '/../src/contract/Response.php',
                'controller\\accountcontroller' => '/../src/controller/AccountController.php',
                'controller\\apicontroller' => '/../src/controller/APIController.php',
                'controller\\btccontroller' => '/../src/controller/BTCController.php',
                'controller\\croncontroller' => '/../src/controller/CronController.php',
                'controller\\dashboardcontroller' => '/../src/controller/DashboardController.php',
                'controller\\fiatcontroller' => '/../src/controller/FIATController.php',
                'controller\\sessioncontroller' => '/../src/controller/SessionController.php',
                'controller\\settingscontroller' => '/../src/controller/SettingsController.php',
                'controller\\usercontroller' => '/../src/controller/UserController.php',
                'controller\\vouchercontroller' => '/../src/controller/VoucherController.php',
                'database\\dbcontroller' => '/../src/database/DBController.php',
                'database\\rediswrapper' => '/../src/database/RedisWrapper.php',
                'helper\\utility' => '/../src/helper/Utility.php',
                'model\\model' => '/../src/model/Model.php',
                'paystack\\payment\\payment' => '/../src/providers/Paystack/Payment/Payment.php',
                'paystack\\paystack' => '/../src/providers/Paystack/Paystack.php',
                'plaf\\actionlistener' => '/../src/service/plaf/ActionListener.php',
                'test\\controller\\usercontrollertest' => '/unit/UserControllerTest.php',
                'view\\email' => '/../src/view/Email.php',
                'view\\page' => '/../src/view/Page.php',
                'view\\pageelement' => '/../src/view/PageElement.php',
                'view\\pagex' => '/../src/view/PageX.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
