version: "3.9"
services:
    web:
        build:
            context: ../../
            dockerfile: devops/deploy/web/Dockerfile
        container_name: php74
        depends_on:
            - db
        volumes:
            - ../../:/var/www/app/
        ports:
            - 8000:80
    db:
        container_name: mysql8
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: onec_user_info
            MYSQL_USER: mysql_dba
            MYSQL_PASSWORD: 7~6%{ipu[n1w
        ports:
            - 6033:3306
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/mysql/data:/var/lib/mysql
      
      # cache:
      #   image: redis:latest 
            
            
      db-backup-periodic:
        build: ./db-backup-periodic
        container_name: db-backup-periodic
        depends_on:
            - db
        # profiles:
        #   - init
        environment:
            MYSQL_CONTAINER_NAME: db
            MYSQL_DATABASE: onec_user_info
            MYSQL_ROOT_PASSWORD: password #${MYSQL_ROOT_PASSWORD}
            DB_BACKUP_FOLDER: /opt/mysql/backup
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/mysql/backup:/opt/mysql/backup
        command: crond -f -d 8
        restart: always
