<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'comm\\comm' => '/service/comm/Comm.php',
                'comm\\link' => '/service/comm/Link.php',
                'comm\\mailer' => '/service/comm/Mailer.php',
                'comm\\messager' => '/service/comm/Messager.php',
                'comm\\notification' => '/service/comm/Notification.php',
                'contract\\controller' => '/contract/Controller.php',
                'contract\\event' => '/contract/Event.php',
                'contract\\eventlistener' => '/contract/EventListener.php',
                'contract\\message' => '/contract/Message.php',
                'contract\\quantity' => '/contract/Quantity.php',
                'contract\\request' => '/contract/Request.php',
                'contract\\response' => '/contract/Response.php',
                'controller\\accountcontroller' => '/controller/AccountController.php',
                'controller\\apicontroller' => '/controller/APIController.php',
                'controller\\btccontroller' => '/controller/BTCController.php',
                'controller\\croncontroller' => '/controller/CronController.php',
                'controller\\dashboardcontroller' => '/controller/DashboardController.php',
                'controller\\fiatcontroller' => '/controller/FIATController.php',
                'controller\\sessioncontroller' => '/controller/SessionController.php',
                'controller\\settingscontroller' => '/controller/SettingsController.php',
                'controller\\usercontroller' => '/controller/UserController.php',
                'controller\\vouchercontroller' => '/controller/VoucherController.php',
                'database\\dbcontroller' => '/database/DBController.php',
                'database\\rediswrapper' => '/database/RedisWrapper.php',
                'helper\\utility' => '/helper/Utility.php',
                'model\\model' => '/model/Model.php',
                'paystack\\payment\\payment' => '/providers/Paystack/Payment/Payment.php',
                'paystack\\paystack' => '/providers/Paystack/Paystack.php',
                'plaf\\actionlistener' => '/service/plaf/ActionListener.php',
                'view\\email' => '/view/Email.php',
                'view\\page' => '/view/Page.php',
                'view\\pageelement' => '/view/PageElement.php',
                'view\\pagex' => '/view/PageX.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
